# Generated by Django 5.0.4 on 2024-05-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorizacao_nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo_nome', models.CharField(max_length=100, unique=True)),
                ('estilo_dificuldade', models.CharField(choices=[('FÁCIL', 'Fácil'), ('MÉDIA', 'Média'), ('DIFÍCIL', 'Difícil')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_nome', models.CharField(max_length=100, unique=True)),
                ('promo_data_inicio', models.DateField()),
                ('promo_data_fim', models.DateTimeField()),
                ('promo_ativa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_nome', models.CharField(max_length=100, unique=True)),
                ('tamanho_dimensao', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arte_nome', models.CharField(max_length=100)),
                ('arte_preco', models.FloatField(max_length=8)),
                ('arte_qntd_sessoes', models.IntegerField(blank=True, default=0, max_length=2, null=True)),
                ('arte_wishlist', models.BooleanField(default=False)),
                ('arte_imagem', models.ImageField(blank=True, upload_to='artes/%Y/<django.db.models.fields.CharField>/')),
                ('arte_colorizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colorizacao_arte', to='galeria.colorizacao')),
                ('arte_estilo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estilo_arte', to='galeria.estilo')),
                ('arte_promocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocao_arte', to='galeria.promocao')),
            ],
        ),
        migrations.CreateModel(
            name='Tatuagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tatuagem_nome', models.CharField(max_length=100)),
                ('tatuagem_nome_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('tatuagem_data', models.DateField()),
                ('tatuagem_lugar_corpo', models.CharField(blank=True, max_length=100, null=True)),
                ('tatuagem_local_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('tatuagem_preco', models.FloatField(max_length=8)),
                ('tatuagem_duracao_servico', models.IntegerField(blank=True, max_length=3, null=True)),
                ('tatuagem_imagem', models.ImageField(blank=True, upload_to='tatuagem/%Y/<django.db.models.fields.CharField>/')),
                ('tatuagem_colorizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colorizacao_tatuagem', to='galeria.colorizacao')),
                ('tatuagem_estilo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estilo_tatuagem', to='galeria.estilo')),
                ('tatuagem_tamanho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamanho_tatuagem', to='galeria.tamanho')),
            ],
        ),
    ]
