# Generated by Django 5.0.4 on 2024-05-04 15:58

import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_arte_arte_promocao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='arte_imagem',
            field=models.ImageField(blank=True, upload_to=galeria.models.Arte.get_path),
        ),
        migrations.AlterField(
            model_name='tatuagem',
            name='tatuagem_imagem',
            field=models.ImageField(blank=True, upload_to='tatuagens/%Y/None/'),
        ),
    ]
