# Generated by Django 5.0.4 on 2024-05-05 12:51

import datetime
import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_arte_arte_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatuagem',
            name='tatuagem_data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tatuagem',
            name='tatuagem_imagem',
            field=models.ImageField(blank=True, upload_to=galeria.models.Tatuagem.get_path),
        ),
    ]
