# Generated by Django 5.0.4 on 2024-05-18 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_tatuagem_tatuagem_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanho',
            name='tamanho_dimensao',
        ),
        migrations.AddField(
            model_name='arte',
            name='arte_tamanho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamanho_arte', to='galeria.tamanho'),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='tamanho_max',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='tamanho_min',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arte',
            name='arte_preco',
            field=models.FloatField(max_length=8.2),
        ),
        migrations.AlterField(
            model_name='tatuagem',
            name='tatuagem_preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
