# Generated by Django 5.0.4 on 2024-05-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_remove_tamanho_tamanho_dimensao_arte_arte_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='arte_lugar_corpo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arte',
            name='arte_qntd_sessoes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
